### ISSUE TITLE
Clarification about code block wrap width

### ISSUE THREAD

**Issue by AB1908** [jez/tufte-pandoc-css#7]
![image](https://user-images.githubusercontent.com/14124383/129561722-590114d9-75ad-498a-bd94-56ee5b075256.png)
The first code block is wrapped properly while the second is not. Is this a design choice? If so, would you mind explaining the rationale behind it?

On a different note, many thanks for your work especially on pandoc-sidenotes. It is a supremely useful library and has saved me many hours of experimentation.

**Comment by jez** [comment]
> The first code block is wrapped properly while the second is not. Is this a design choice? If so, would you mind explaining the rationale behind it?

https://github.com/jez/tufte-pandoc-css/blame/master/docs/index.md#L58

The first code block is a normal one, the second is a full width one. In the above example it doesn't matter, because at most desktop screen widths the code snippet will fit without scrolling or wrapping anyways. But tufte-css has `.fullwidth` classes for other non-prose elements, so I figured I'd do the work to make `.fullwidth` work for figures too.
